
import React from 'react';
import { 
  LayoutDashboard, 
  CreditCard, 
  AlertTriangle, 
  RotateCcw, 
  Settings2, 
  Activity, 
  FileText, 
  Settings,
  ChevronRight,
  ChevronDown,
  Search,
  Bell,
  User,
  Menu,
  X,
  RefreshCw,
  Plus,
  Filter,
  ArrowUpRight,
  ArrowDownRight,
  Clock,
  ExternalLink,
  Lock,
  Moon,
  Sun,
  Trash2,
  CheckCircle2,
  XCircle,
  AlertCircle,
  HelpCircle,
  MoreVertical
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Payments: CreditCard,
  Alerts: AlertTriangle,
  Incident: RotateCcw,
  Rules: Settings2,
  Health: Activity,
  Logs: FileText,
  Settings: Settings,
  ChevronRight,
  ChevronDown,
  Search,
  Bell,
  User,
  Menu,
  X,
  Refresh: RefreshCw,
  Plus,
  Filter,
  TrendUp: ArrowUpRight,
  TrendDown: ArrowDownRight,
  Clock,
  ExternalLink,
  Lock,
  Moon,
  Sun,
  Trash: Trash2,
  Success: CheckCircle2,
  Error: XCircle,
  Warning: AlertCircle,
  Info: HelpCircle,
  More: MoreVertical
};
